import { filterData } from "../resources/utils/js-utils";

const data = [{"id":"3e73187d-88c0-4586-81e5-27de6547acad","first_name":"Jess","last_name":null,"text":"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.","email":"jpinkett0@zdnet.com","backgroundColor":"#861b5b","avatar":"https://robohash.org/occaecatiofficiacum.jpg?size=200x200&set=set1","avatar_large":null},
{"id":"80946460-de9a-438b-897c-b46cb2a77718","first_name":"Midge","last_name":"Skillington","text":"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.","email":"mskillington1@nifty.com","backgroundColor":"#4084b5","avatar":"https://robohash.org/quosrerumnisi.jpg?size=200x200&set=set1","avatar_large":"https://robohash.org/exblanditiismodi.png?size=3840x2160&set=set1&bgset=bg1"},
{"id":"92a860c4-4c8a-41b2-a555-3fb6a93ecba1","first_name":"Codee","last_name":"Hanner","text":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","email":"channer2@xrea.com","backgroundColor":"#54ff9e","avatar":"https://robohash.org/debitissaepeaut.jpg?size=200x200&set=set1","avatar_large":"https://robohash.org/providentetipsa.png?size=3840x2160&set=set1&bgset=bg1"}];
const expectedResult = [
    {"id":"80946460-de9a-438b-897c-b46cb2a77718","first_name":"Midge","last_name":"Skillington","text":"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.","email":"mskillington1@nifty.com","backgroundColor":"#4084b5","avatar":"https://robohash.org/quosrerumnisi.jpg?size=200x200&set=set1","avatar_large":"https://robohash.org/exblanditiismodi.png?size=3840x2160&set=set1&bgset=bg1"},
    {"id":"92a860c4-4c8a-41b2-a555-3fb6a93ecba1","first_name":"Codee","last_name":"Hanner","text":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","email":"channer2@xrea.com","backgroundColor":"#54ff9e","avatar":"https://robohash.org/debitissaepeaut.jpg?size=200x200&set=set1","avatar_large":"https://robohash.org/providentetipsa.png?size=3840x2160&set=set1&bgset=bg1"}
]
test('filter out null avatar_image from user list', () => {
    expect(filterData(data)).toEqual(expectedResult)
})